### ISSUE TITLE
不支持影客

### ISSUE THREAD

**Issue by reidyou** [Juszoe/flexget-nexusphp#1]
2019-08-14 22:05 VERBOSE  details       yingk           Produced 10 entries.
2019-08-14 22:05 VERBOSE  details       yingk           Summary - Accepted: 0 (Rejected: 0 Undecided: 10 Failed: 0)
2019-08-14 22:10 WARNING  manager                       Your locale declares ascii as the filesystem encoding. Any plugins reading filenames from disk will not work properly for filenames containing non-ascii characters. Make sure your locale env variables are set up correctly for the environment which is launching FlexGet.

**Comment by reidyou** [comment]
相关HTML代码


<tr><td id="outer" align="center" class="outer" style="padding-top: 20px; padding-bottom: 20px">
--
  | <div align="center" style="margin-bottom: 10px" id="ad_belownav"><font size="3"><span style="color: red;"><b>请勿在公开网络场合讨论本站以及发放本站邀请！（包括但不限于百度贴吧、各类论坛、微博、QQ群）</b></span></font></div><h1 align="center" id="top"><b><span class='tag span_recommendedds'>推荐</span></b><span class='tag span_sources'>美国</span>Great Courses - Economics &amp; Finance<span class='tag span_standards'>720P</span><span class='tag span_teams'>HDTV</span><span class='tag span_processings'>AC3/DD</span><span class='tag span_codecs'>X.264/H.264/AVC</span><b><span class='tag span_twoupfreels' >2X免费：<b><span title="2019-08-21 00:00:00">6天1时</span></b></span></b></h1><table width="98%" cellspacing="0" cellpadding="5"><tr><td class="rowhead nowrap" valign="top" align="right">操作</td><td class="rowfollow" valign="top" align="left"><a title="下载种子" href="download.php?id=10036"><img class="dt_download" src="/pic/trans.gif" alt="download" />&nbsp;<b><font class="small">下载种子<font color='red'>[未完成]</font></font></b></a>&nbsp;\|&nbsp;<a id="bookmark0" href="javascript: bookmarktext(10036,0);"><SPAN id="unbookmarked0" ><img class="delbookmark" src="/pic/trans.gif" alt="Unbookmarked" title="添加收藏" /><b><font class="small">&nbsp;添加收藏</font></b></SPAN><SPAN id="bookmarked0"   style="display: none;"><img class="bookmark" src="/pic/trans.gif" alt="Bookmarked" title="去除收藏" /><b><font class="small">&nbsp;去除收藏</font></b></SPAN></a>&nbsp;\|&nbsp;<a title="上传字幕/附件"  href="javascript:document.subtitles.submit()" ><img class="sticky" src="/pic/trans.gif" alt="upload" />&nbsp;<b><font class="small">上传字幕/附件</font></b></a>&nbsp;\|&nbsp;<a target="_blank" title="购买种子的促销及置顶" href="bysppos.php?id=10036"><img class="buddylist" src="/pic/trans.gif" alt="buy" />&nbsp;<b><font class="small">竞价种子</font></b></a>&nbsp;\|&nbsp;<a title="举报该种子违反了规则" href="report.php?torrent=10036"><img class="dt_report" src="/pic/trans.gif" alt="report" />&nbsp;<b><font class="small">举报种子</font></b></a><span style="display: none"><form method="post" action="subtitles.php" name="subtitles"><input type="hidden" name="torrent_name" value="Great Courses - Economics & Finance" /><input type="hidden" name="detail_torrent_id" value="10036" /><input type="hidden" name="in_detail" value="in_detail" /></form></span></td></tr>
  | <tr><td class="rowhead nowrap" valign="top" align="right">种子链接</td><td class="rowfollow" valign="top" align="left"><a title=" 此为你的直接下载链接，方便远程任务使用，切勿告诉他人！(鼠标右键复制链接)" href="/download.php?id=10036&passkey=xyz"><img class="dt_download" src="/pic/trans.gif" alt="download" />&nbsp;<b><font class="small"><span style="color:#f00; font-weight:bold;">[此为你的直接下载链接，方便远程任务使用，切勿告诉他人！]</span></font></b></a></td></tr>
  | <tr><td class="rowhead nowrap" valign="top" align="right">种子认领<a target="_blank" href="/forums.php?action=viewtopic&forumid=1&topicid=123" style="background: #FF0000;color:#fff"><b>？</b></a></td><td class="rowfollow" valign="top" align="left"><a href="viewclaims.php?add_torrent_id=10036">[ 认领种子 ]</a><a   href="viewclaims.php?torrent_id=10036">[查看认领详情:0]</a></td></tr>
  | <tr><td class="rowhead nowrap" valign="top" align="right">副标题</td><td class="rowfollow" valign="top" align="left">TTC教学视频分类合集8--经济&amp;金融。</td></tr>
  | <tr><td width="1%" class="rowhead nowrap" valign="top" align="right">种子信息</td><td width="99%" class="rowfollow" valign="top" align="left">由&nbsp;<span class="nowrap"><a  href="userdetails.php?id=6967" class='EliteUser_Name' ><b>Mirac1e</b></a> (<b class='EliteUser_Name' >(连长)Elite User</b>)</span>&nbsp;发布于<span title="2019-08-14 10:49:35">11时27分前</span>&nbsp;&nbsp;&nbsp;<span style="display:inline-table;height:14px;line-height: 12px;padding-right: 5px"></span></td></tr>
  | <tr><td width="1%" class="rowhead nowrap" valign="top" align="right">基本信息</td><td width="99%" class="rowfollow" valign="top" align="left"><b>类型:</b>&nbsp;学习-经济管理&nbsp;&nbsp;&nbsp;<b><b>大小：</b></b>190.31GB&nbsp;&nbsp;&nbsp;<b>地区:&nbsp;</b>美国&nbsp;&nbsp;&nbsp;<b>媒介:&nbsp;</b>HDTV&nbsp;&nbsp;&nbsp;<b>视频编码:&nbsp;</b>X.264/H.264/AVC&nbsp;&nbsp;&nbsp;<b>音频编码:&nbsp;</b>AC3/DD&nbsp;&nbsp;&nbsp;<b>分辨率:&nbsp;</b>720P</td></tr>

**Comment by Juszoe** [comment]
感谢反馈，目前只收到了2xfree，能否提供所有的优惠信息呢？

**Comment by reidyou** [comment]
7龙珠收集齐了：）
[2X.txt](https://github.com/Juszoe/flexget-nexusphp/files/3509836/2X.txt)
[2X50%.txt](https://github.com/Juszoe/flexget-nexusphp/files/3509837/2X50.txt)
[2X免费.txt](https://github.com/Juszoe/flexget-nexusphp/files/3509839/2X.txt)
[30%.txt](https://github.com/Juszoe/flexget-nexusphp/files/3509840/30.txt)
[50%.txt](https://github.com/Juszoe/flexget-nexusphp/files/3509841/50.txt)
[免费.txt](https://github.com/Juszoe/flexget-nexusphp/files/3509842/default.txt)
[普通.txt](https://github.com/Juszoe/flexget-nexusphp/files/3509843/default.txt)

**Comment by Juszoe** [comment]
已经适配，麻烦测试1.1版本

**Comment by reidyou** [comment]
> 已经适配，麻烦测试1.1版本

已测试通过，谢谢！

**Comment by reidyou** [comment]
北洋园HTML代码，请大佬适配
[2X.txt](https://github.com/Juszoe/flexget-nexusphp/files/3512551/2X.txt)
[2X50%.txt](https://github.com/Juszoe/flexget-nexusphp/files/3512552/2X50.txt)
[2X免费.txt](https://github.com/Juszoe/flexget-nexusphp/files/3512553/2X.txt)
[30%.txt](https://github.com/Juszoe/flexget-nexusphp/files/3512554/30.txt)
[50%.txt](https://github.com/Juszoe/flexget-nexusphp/files/3512555/50.txt)
[免费.txt](https://github.com/Juszoe/flexget-nexusphp/files/3512556/default.txt)
[普通.txt](https://github.com/Juszoe/flexget-nexusphp/files/3512557/default.txt)

**Comment by Juszoe** [comment]
看了北洋园的代码，理论是支持的呀

**Comment by reidyou** [comment]
同样的配置，馒头铂金家都可以，北洋园不行，日志全部都是Undecided。代码我也看过，北洋园并未修改discount标签，但确实不行，不知道是哪的问题。你可以在代码里面加些日志打印信息，发给我测试一下

**Comment by Juszoe** [comment]
1.1 修改为debug版，麻烦测试

**Comment by reidyou** [comment]
> 1.1 修改为debug版，麻烦测试
50个种子全reject了，筛选不到
[tjupt-log.txt](https://github.com/Juszoe/flexget-nexusphp/files/3516425/tjupt-log.txt)

**Comment by Juszoe** [comment]
> 同样的配置，馒头铂金家都可以，北洋园不行，日志全部都是Undecided。代码我也看过，北洋园并未修改discount标签，但确实不行，不知道是哪的问题。你可以在代码里面加些日志打印信息，发给我测试一下

1.1重新修改，再次测试一下

**Comment by reidyou** [comment]
> > 同样的配置，馒头铂金家都可以，北洋园不行，日志全部都是Undecided。代码我也看过，北洋园并未修改discount标签，但确实不行，不知道是哪的问题。你可以在代码里面加些日志打印信息，发给我测试一下
> 
> 1.1重新修改，再次测试一下

0821：最新的1.1测试了一下，跟之前的打印信息一样，全部只有这种dismatch信息，没有其他debug输出。

2019-08-21 22:15 VERBOSE  task                          REJECTED: `[美国][黑衣人：全球追缉][Men.in.Black.International.2019.INTERNAL.HDR.2160p.WEB-DL.H265-DEFLATE]` by nexusphp plugin because none does not match discount

大佬方便的话，加个QQ沟通1678563103
