### ISSUE TITLE
能否加入文件大小过滤的选项

### ISSUE THREAD

**Issue by tyhunter** [Juszoe/flexget-nexusphp#17]
因为用1T的OL刷，所以不太敢下免费大种，Flexget有个Content-Size的选项，可以过滤体积大于或者小于设置的种子，但是配置了插件后，content-size不起作用了
例如我设置了只下载1M-100G的种子
    content_size:
      min: 1
      max: 100000  
      strict: no

但是execute的时候，这段规则被无视了，超过100G的仍然可以被下载回来添加到deluge

**Comment by Juszoe** [comment]
建议设置严格模式strict: yes

**Comment by tyhunter** [comment]
已解决，感谢大佬
