### ISSUE TITLE
关于U2的Other优惠

### ISSUE THREAD

**Issue by sun128764** [Juszoe/flexget-nexusphp#24]
U2中的Other优惠一般为上传2.33,下载0。个人认为比较接近2Xfree类别。希望可以更改到2Xfree类别中，以方便订阅者下载全部免费种子。

**Comment by xfl03** [comment]
```py
'<td.*?top.*?pro_custom.*?优惠历史.*?</td>': '2x'
```
看代码是目前把Other优惠解析成2x

**Comment by kafuuchino-s** [comment]
自己加个2.33up0.00down的筛选就行了

**Comment by xfl03** [comment]
@kafuuchino-s 希望可以详细说一下

**Comment by kafuuchino-s** [comment]
[nexusphp.zip](https://github.com/Juszoe/flexget-nexusphp/files/4002668/nexusphp.zip)
你直接用这个吧，对比一下代码就能发现我只是照着其他优惠条件加了个2.33up0.00down的优惠，
你到时在flexget配置文件中的discout那项再加个2.33up0.00down的选项就行了。
![image](https://user-images.githubusercontent.com/51790568/71478623-8c410e80-282b-11ea-8991-5d90814f6369.png)

**Comment by Juszoe** [comment]
@sun128764 已从 2x 修改为 2xfree，之前还以为要记下载

**Comment by aquestionx** [comment]
> 
> 
> [nexusphp.zip](https://github.com/Juszoe/flexget-nexusphp/files/4002668/nexusphp.zip)
> 你直接用这个吧，对比一下代码就能发现我只是照着其他优惠条件加了个2.33up0.00down的优惠，
> 你到时在flexget配置文件中的discout那项再加个2.33up0.00down的选项就行了。
> ![image](https://user-images.githubusercontent.com/51790568/71478623-8c410e80-282b-11ea-8991-5d90814f6369.png)

我尝试着使用nexusphp在U2下载免费种，free,2xfree,2.33这种，我配置了nexusphp但仍然没办法把免费种筛选进来，我查log还是提示
`......by nexusphp plugin because none does not match discount`

我不懂编程，nexusphp.py里面的东西打开了我看了也一脸懵，我猜测是不是因为U2的免下载不是因为在种子发布时系统自动给的，而是用户用积分自己换的，所以在刚开始时rss里抓不到。以下是我的Flexget配置，能否指导一下如何在U2抓免费种，谢谢。

![fl](https://user-images.githubusercontent.com/60572624/84867205-5f203b00-b0ad-11ea-914d-a418f221c628.JPG)

**Comment by Juszoe** [comment]
@aquestionx U2这种情况是因为，优惠是发布之后才添加的，如果没有优惠的时候就执行了Flexget就会缓存“None”的结果。可以设置`remember: no`取消缓存

**Comment by aquestionx** [comment]
> 
> 
> @aquestionx U2这种情况是因为，优惠是发布之后才添加的，如果没有优惠的时候就执行了Flexget就会缓存“None”的结果。可以设置`remember: no`取消缓存

谢谢作者的回答，但我试了还是不行，作为对比我用了一个相似的配置去PTH去试是能下载到免费种的，flexget的输出结果和两个站的设置见下方，你能再帮我看一下吗

flexget输出的结果
U2
```2020-06-17 22:13:35 VERBOSE  details       U2              Produced 10 entries.```
```2020-06-17 22:13:37 VERBOSE  task                          REJECTED: `ABCD` by nexusphp plugin because none does not match discount```
PTH
```2020-06-17 22:15:31 VERBOSE  details       pthome          Produced 10 entries.```
```2020-06-17 22:15:34 VERBOSE  task                          ACCEPTED: `EFGH` by nexusphp plugin```
```2020-06-17 22:15:34 INFO     remember_rej                  Remembering rejection of `IJKL` ```
```2020-06-17 22:15:34 VERBOSE  task                          REJECTED: `IJKL` by nexusphp plugin because 50% does not match discount```

![U2](https://user-images.githubusercontent.com/60572624/84914808-a4b12800-b0ee-11ea-9ec7-f4b6a6c7f7c8.JPG)
![PTH](https://user-images.githubusercontent.com/60572624/84914816-a7138200-b0ee-11ea-867b-ec5c8b6a2c43.JPG)
