### ISSUE TITLE
若种子页面存在【其他版本】会错误判断

### ISSUE THREAD

**Issue by HUSH-Wang** [Juszoe/flexget-nexusphp#26]
目前发现在TJUPT种子详情页面的【其他版本】会导致判断错误
![123](https://user-images.githubusercontent.com/22000777/71727251-9ccd3680-2e74-11ea-9016-7354f5d66cf5.png)

**Comment by Juszoe** [comment]
我测试没有发现问题，是否用的旧版本，几个月前的版本是有这种BUG

**Comment by HUSH-Wang** [comment]
就是Github上的最新的，昨天更新之前的版本。

**Comment by Juszoe** [comment]
@HUSH-Wang 麻烦提供一下出问题的种子id，我去测试一下

**Comment by HUSH-Wang** [comment]
https://www.tjupt.org/details.php?id=204060
可以试一下这个，其他版本里有一个是Free的。

**Comment by Juszoe** [comment]
我测试仍然正常

**Comment by HUSH-Wang** [comment]
好吧，我再试试看，有问题的话再开。
