### ISSUE TITLE
PT网站启用cf5秒盾后，插件拉取频繁返回503

### ISSUE THREAD

**Issue by tyhunter** [Juszoe/flexget-nexusphp#28]
请教下作者 这种情况该如何解决

**Comment by Aniverse** [comment]
网站开五秒盾可能就是因为抓 free 的人太多了……

**Comment by yang0026** [comment]
> 
> 
> 请教下作者 这种情况该如何解决

装cloudscraper，然后把nexusphp里requests换成cloudscraper里的方法就行了

**Comment by Rhilip** [comment]
> > 请教下作者 这种情况该如何解决
> 
> 装cloudscraper，然后把nexusphp里requests换成cloudscraper里的方法就行了

活生生的 **我们只想封杀PGone，而他的粉丝想他死**
