### ISSUE TITLE
合理限制对details_page页面请求

### ISSUE THREAD

**Issue by Rhilip** [Juszoe/flexget-nexusphp#29]
我们观察到来自该flexget插件用户对`details.php`以及`viewpeerlist.php`页面**瞬时大量请求**，请考虑增加sleep、local cache或者直接从种子列表页获取并分析优惠信息、做种情况等信息。
否则我们将认为其用户行为违反了网站相关规则 `对网站使用自动脚本或工具危害到网站正常运转`，对相关用户进行警告或者ban号。

OurBits & YingK, Rhilip

**Comment by Juszoe** [comment]
十分抱歉给贵站带来困扰。其实sleep源于用户设置的启动flexget间隔，也有类似local cache的功能，只是瞬时大量请求可能没考虑到网站的负载，近期会作出修改，同时我也会呼吁本插件用户更新并设置合适的参数
