### ISSUE TITLE
flexget日志中频繁报错

### ISSUE THREAD

**Issue by noginger** [Juszoe/flexget-nexusphp#4]
Unable to download the RSS for task cmctAuto (https://springsunday.net/torrentrss.php?rows=50&linktype=dl&passkey=我的passkey): HTTPSConnectionPool(host='springsunday.net', port=443): Max retries exceeded with url: /torrentrss.php?rows=50&linktype=dl&passkey=我的passkey(Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f630bec84a8>, 'Connection to springsunday.net timed out. (connect timeout=60)'))

我添加了三个站（chd，ssd，hdsky），均会报这个错误，同时报错之后下载种子就会失败

**Comment by Juszoe** [comment]
无法下载rss，你和这些站点连接性不佳，多试几次
