### ISSUE TITLE
U2没有匹配到优惠

### ISSUE THREAD

**Issue by Seitazzo** [Juszoe/flexget-nexusphp#41]
使用1.3版本，

[flexget.log](https://github.com/Juszoe/flexget-nexusphp/files/4855805/flexget.log)
[config.yml.log](https://github.com/Juszoe/flexget-nexusphp/files/4855808/config.yml.log)

(config.yml.log删掉.log)

与此同时，网站显示优惠情况为，
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/31207151/86205712-28621e80-bb9d-11ea-8f0e-48bda1c3de82.png">

**Comment by Seitazzo** [comment]
2.33x 0.00x那个不知道怎么写，普通的2xfree这个就正常了，希望作者更新
adapter: 
    2xfree: pro_free2up

**Comment by Seitazzo** [comment]
并且出现了类似[https://github.com/Juszoe/flexget-nexusphp/issues/8](url)的问题

**Comment by mylovesaber** [comment]
你改了什么地方啊？我看源码里面的确有other的信息啊

**Comment by Seitazzo** [comment]
原本无论是在discount写了free和2xfree还是没写，都会一律被reject掉，自己加了
adapter:
2xfree: pro_free2up
以后，才能让2xfree的种子被accept，但是种子详情页的其它种子一旦包含2xfree，无论该种子是什么优惠类型都会被accept，这样会徒增下载量

**Comment by Juszoe** [comment]
u2默认匹配机制如下，实际上我自己使用时会种子有被reject的情况，猜测是种子出来时并不是free，优惠信息是后来添加的，而插件会对优惠信息进行缓存。
``` python
'u2.dmhy': {
                '<td.*?top.*?pro_free.*?优惠历史.*?</td>': 'free',
                '<td.*?top.*?pro_2up.*?优惠历史.*?</td>': '2x',
                '<td.*?top.*?pro_free2up.*?优惠历史.*?</td>': '2xfree',
                '<td.*?top.*?pro_30pctdown.*?优惠历史.*?</td>': '30%',
                '<td.*?top.*?pro_50pctdown.*?优惠历史.*?</td>': '50%',
                '<td.*?top.*?pro_50pctdown2up.*?优惠历史.*?</td>': '2x50%',
                '<td.*?top.*?pro_custom.*?优惠历史.*?</td>': '2xfree'
}
```

**Comment by Seitazzo** [comment]
因此我把remember改为no，但在肉眼确认种子属于2xfree后运行仍然reject。
添加adapter后能够accept 2xfree种子，但也有不是2xfree的种子混进来。

**Comment by Juszoe** [comment]
我大概知道原因了，你使用的是繁体页面，因此无法匹配成功，可以在代码中将上述字段修改为繁体即可。后续我会改进不同语言的差异。
简单的设置pro_free2up是会误判的，需要设置为
```
<td.*?top.*?pro_free2up.*?優惠歷史.*?</td>
```

**Comment by Seitazzo** [comment]
谢谢，我先修改简体中文测试一下

**Comment by Seitazzo** [comment]
[アーカイブ.zip](https://github.com/Juszoe/flexget-nexusphp/files/4923443/default.zip)
已修改nexusphp.py字段为繁体中文，并设置优惠类型为free和2xfree，依然reject全部
在u2修改网站语言和nexusphp.py为简体中文后再测试

**Comment by Juszoe** [comment]
有些奇怪，配置和代码都没什么问题。
现在u2全站free，刚刚自己试了下，是可以全部Accept的。
插件是采用正则匹配来匹配free的，可以在adapter设置，不用修改代码。
再给一个试一下，优惠历史的链接是`promotion.php`，所以按照这个来匹配
```
<td.*?top.*?pro_free2up.*?promotion.*?</td>
```

**Comment by Seitazzo** [comment]
请问是把你给出的那行补到一堆优惠历史的行里面去吗

**Comment by Juszoe** [comment]
> 请问是把你给出的那行补到一堆优惠历史的行里面去吗

新增或修改均可，我更建议在adapter设置，方便一些

**Comment by Seitazzo** [comment]
nexusphp:
(俩空格)discount: ['free','2xfree']
(俩空格)adapter:
(俩空格)(俩空格)2xfree: <td.*?top.*?pro_free2up.*?promotion.*?</td>

加入这个以后无论什么优惠的种子都accept了，查看种子详情发现其它版本中也并没有free和2xfree的种子
当前nexusphp.py的“优惠历史”为简体中文

**Comment by Juszoe** [comment]
经过我的测试，u2填错了cookie不会提示，而是识别为none

**Comment by Seitazzo** [comment]
填错了cookie都还能获取到种子和详情页面的吗...我检查一下cookie

**Comment by Juszoe** [comment]
> 填错了cookie都还能获取到种子和详情页面的吗...我检查一下cookie

不能获取，所以识别为none，其他站都是跳转到登录页面，u2不一样，所以没有警告

**Comment by Seitazzo** [comment]
检查了下的确cookie跟最新的不一样，等待新种子出来测试优惠条件判断

**Comment by Seitazzo** [comment]
更新到最新版本，cookie正确后已经正常运作，谢谢你的耐心指导
