### ISSUE TITLE
U2优惠条件 Other判定不准确(?)

### ISSUE THREAD

**Issue by Seitazzo** [Juszoe/flexget-nexusphp#42]
再次感谢作者之前的帮助，插件到现在一直运行得都很正常。
但是今早发现漏了下载量，检查发现是有一个Other类型的种子混了进来，估计本来将Other识别为2xfree是为了2.33x up/0.00x down优惠的吧，但这一个Other是2.00x up/0.30x down的。
请问可否添加选项排除2.33x/0.00x外的Other类型优惠？

**Comment by Juszoe** [comment]
没想到真有人放魔法不搞2.33/0.00。
已经修复了，这样只有0.00x才会计入2xfree，至于上传肯定比1大的应该无所谓。

**Comment by Seitazzo** [comment]
谢谢，马上去替换
