### ISSUE TITLE
U2疑似识别错误接受其它优惠条件的种子

### ISSUE THREAD

**Issue by Seitazzo** [Juszoe/flexget-nexusphp#44]
检查优惠历史发现accept时间内没有优惠条件也不可能满足seeder范围

https://u2.dmhy.org/details.php?id=39679&hit=1
https://u2.dmhy.org/details.php?id=39693&hit=1

Task dmhy
Title [冷然之天秤][Nil Admirari no Tenbin][ニル・アドミラリの天秤][BDMV][1080p][Vol.1-Vol.4 Fin][AVCHD][自抓]
URL https://u2.dmhy.org/download.php?id=39693&passkey=
Time Thu Jul 23 12:47:30 2020
Details Accepted by accept_all

Task dmhy
Title [心理测量者第3季][Psycho-Pass 3][サイコパス3][BDMV][Vol.03-04 Fin][brutelor@緋月]                                                                           URLhttps://u2.dmhy.org/download.php?id=39679&passkey= 
Time Wed Jul 22 05:07:25 2020
Details Accepted by accept_all  

其中发现所有异常accept的种子都在Details显示Accepted by accept_all，正常的显示Accepted by nexusphp

[config.yml.zip](https://github.com/Juszoe/flexget-nexusphp/files/4963952/config.yml.zip)

**Comment by Juszoe** [comment]
把`accept_all: yes`删除即可，这个插件会接受所有的条目，为啥要加这一行呢

**Comment by Seitazzo** [comment]
我以为不加那行就必须添加标题内容匹配的那些..
