### ISSUE TITLE
OpenCD站 Cookie错误

### ISSUE THREAD

**Issue by Superbia000** [Juszoe/flexget-nexusphp#45]
2020-07-26 01:27:47 VERBOSE  details       OpenCD          Produced 10 entries.
2020-07-26 01:27:54 ERROR    nexusphp      OpenCD          Can't access the site. Your cookie may be wrong!
2020-07-26 01:27:54 ERROR    nexusphp      OpenCD          Can't access the site. Your cookie may be wrong!
2020-07-26 01:27:54 ERROR    nexusphp      OpenCD          Can't access the site. Your cookie may be wrong!
2020-07-26 01:27:54 ERROR    nexusphp      OpenCD          Can't access the site. Your cookie may be wrong!
2020-07-26 01:27:54 ERROR    nexusphp      OpenCD          Can't access the site. Your cookie may be wrong!
2020-07-26 01:27:54 ERROR    nexusphp      OpenCD          Can't access the site. Your cookie may be wrong!
2020-07-26 01:27:54 ERROR    nexusphp      OpenCD          Can't access the site. Your cookie may be wrong!
2020-07-26 01:27:54 ERROR    nexusphp      OpenCD          Can't access the site. Your cookie may be wrong!
2020-07-26 01:27:54 ERROR    nexusphp      OpenCD          Can't access the site. Your cookie may be wrong!
2020-07-26 01:27:54 ERROR    nexusphp      OpenCD          Can't access the site. Your cookie may be wrong!
2020-07-26 01:27:54 VERBOSE  details       OpenCD          Summary - Accepted: 0 (Rejected: 0 Undecided: 10 Failed: 0)

**Comment by Superbia000** [comment]
Cookie通过 Chrome->F12->Network 提取

**Comment by stefaneliu** [comment]
我也是，明明cookie是对的，也按照正确方法去取得的，但是就是报错。。。。

**Comment by Superbia000** [comment]
> 用的是哪个版本，试试老版本会有这个问题吗

1,4 报错，1.0 没问题

**Comment by Superbia000** [comment]
有时间修复吗

**Comment by Juszoe** [comment]
信息量不够，不能定位问题。1.3可用吗

**Comment by Superbia000** [comment]
> 信息量不够，不能定位问题。1.3可用吗

只有 v1.0 和 beta(v0.1) 能爬取种子页面，其他版本都有Cookie错误，不过beta版本不能识别部分优惠

**Comment by Juszoe** [comment]
说明 OpenCD 光靠 Cookie 和 User Agent 还不够，可能需要别的参数。
F12->Network 里查看有没`特别的 Header`，参考 [Flexget 教程](https://flexget.com/Plugins/headers)设置 Headers

**Comment by Superbia000** [comment]
> 说明 OpenCD 光靠 Cookie 和 User Agent 还不够，可能需要别的参数。
> F12->Network 里查看有没`特别的 Header`，参考 [Flexget 教程](https://flexget.com/Plugins/headers)设置 Headers

![image](https://user-images.githubusercontent.com/24918410/89419290-caa88f80-d763-11ea-8bd7-e4b86d1ae392.png)
是这个吗，都试过一次，不行啊

**Comment by Juszoe** [comment]
也许有反爬措施，我也没办法测试，如果真有反爬的话，还是尊重站点规则不要使用插件为好

**Comment by Superbia000** [comment]
> 也许有反爬措施，我也没办法测试，如果真有反爬的话，还是尊重站点规则不要使用插件为好

我发现只需要把 1.4 的：
`detail_page = task.requests.get(link, headers=headers, timeout=20)`

替换为1.0 的：
`detail_page = task.requests.get(link, headers=headers, allow_redirects=False)`

就不报错了。

**Comment by stefaneliu** [comment]
> > 也许有反爬措施，我也没办法测试，如果真有反爬的话，还是尊重站点规则不要使用插件为好
> 
> 
> 
> 我发现只需要把 1.4 的：
> 
> `detail_page = task.requests.get(link, headers=headers, timeout=20)`
> 
> 
> 
> 替换为1.0 的：
> 
> `detail_page = task.requests.get(link, headers=headers, allow_redirects=False)`
> 
> 
> 
> 就不报错了。

兄弟，我试了一下还是报错。除了改这个detailspage之外，你还改了别的什么吗？

**Comment by Superbia000** [comment]
> > > 也许有反爬措施，我也没办法测试，如果真有反爬的话，还是尊重站点规则不要使用插件为好
> > 
> > 
> > 我发现只需要把 1.4 的：
> > `detail_page = task.requests.get(link, headers=headers, timeout=20)`
> > 替换为1.0 的：
> > `detail_page = task.requests.get(link, headers=headers, allow_redirects=False)`
> > 就不报错了。
> 
> 兄弟，我试了一下还是报错。除了改这个detailspage之外，你还改了别的什么吗？

就改下那段，试试最新的1.4
![image](https://user-images.githubusercontent.com/24918410/89524778-baea8300-d817-11ea-8cff-192326ea1d55.png)

**Comment by Superbia000** [comment]
不

> > 也许有反爬措施，我也没办法测试，如果真有反爬的话，还是尊重站点规则不要使用插件为好
> 
> 我发现只需要把 1.4 的：
> `detail_page = task.requests.get(link, headers=headers, timeout=20)`
> 
> 替换为1.0 的：
> `detail_page = task.requests.get(link, headers=headers, allow_redirects=False)`
> 
> 就不报错了。

不过好像适配不到优惠

HTML:
`<div class="title">Bertie Page Clinic - French Tickler 2012 - FLAC Multi File - zyprexia@OpenCD <img class="pro_free" src="pic/trans.gif" alt="Free" onmouseover="domTT_activate(this, event, 'content', '<b><font class=&quot;free&quot;>免費</font></b>剩餘時間：<b><span title=&quot;2020-08-08 14:02:50&quot;>1天16時</span></b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);" id="__autoId1"></div>`

**Comment by Juszoe** [comment]
> > 也许有反爬措施，我也没办法测试，如果真有反爬的话，还是尊重站点规则不要使用插件为好
> 
> 我发现只需要把 1.4 的：
> `detail_page = task.requests.get(link, headers=headers, timeout=20)`
> 
> 替换为1.0 的：
> `detail_page = task.requests.get(link, headers=headers, allow_redirects=False)`
> 
> 就不报错了。

这样改能识别到优惠吗？站点要求强制跳转，`allow_redirects=False`不会继续跳转，按理说应该什么信息也得不到吧

**Comment by Superbia000** [comment]
> > > 也许有反爬措施，我也没办法测试，如果真有反爬的话，还是尊重站点规则不要使用插件为好
> > 
> > 
> > 我发现只需要把 1.4 的：
> > `detail_page = task.requests.get(link, headers=headers, timeout=20)`
> > 替换为1.0 的：
> > `detail_page = task.requests.get(link, headers=headers, allow_redirects=False)`
> > 就不报错了。
> 
> 这样改能识别到优惠吗？站点要求强制跳转，`allow_redirects=False`不会继续跳转，按理说应该什么信息也得不到吧

是的...

**Comment by huxuan** [comment]
临时的wrokaround，在1.4版本上试了应该没问题，在
```
        detail_page = task.requests.get(link, headers=headers, timeout=20)  # 详情
```
前添加一行
```
        link = link.replace('details.php', 'plugin_details.php')
```
即可。

后来调试发现问题在于直接代码请求 `https://open.cd/details.php?id=XXX` 会先跳转 `https://open.cd/plugin_details.php?id=XXX`然后再跳转到login页面，但是直接请求`https://open.cd/plugin_details.php?id=XXX`就不会有类似的问题，所以只能针对于OpenCD这样临时hack。

另，附上OpenCD对应的adapter
```
      adapter:
        2x50%: pro_50pctdown2up
        2x: pro_2up
        2xfree: pro_free2up
        30%: pro_30pctdown
        50%: pro_50pctdown
        free: pro_free
```
