### ISSUE TITLE
TTG 出现maybe a login page

### ISSUE THREAD

**Issue by matthkewk** [Juszoe/flexget-nexusphp#48]
使用其它站都是正常的，今天想试试TTG就一直失败，研究了很久还是不行，加了代码verify_ssl_certificates: no也问题依旧，请问下怎么解决?
![QQ截图20200801222457](https://user-images.githubusercontent.com/67943258/89103669-067ee480-d446-11ea-8b8b-ea46001bb8da.png)

**Comment by Juszoe** [comment]
rss的链接有问题，确保是客户端使用的链接

**Comment by matthkewk** [comment]
大神请收下我的膝盖，搞了一下午……习惯性选择了下面一个rss地址。。。
