### ISSUE TITLE
flexget日志中频繁报错2

### ISSUE THREAD

**Issue by noginger** [Juszoe/flexget-nexusphp#5]
Execution of job "* (trigger: interval[0:05:00], next run at: 2019-08-22 14:51:49 UTC)" skipped: maximum number of running instances reached (1)

我添加了3个任务，间隔是10分钟执行一次，是不是频率太高了？

**Comment by Juszoe** [comment]
网上解释说，任务开始执行就会计时，当任务执行时间超过定时间隔，就会跳过下次执行
[参考](https://www.jianshu.com/p/462bdf8e6a89)
