### ISSUE TITLE
CHD 新增了HR规则，目前的HR规则还无法兼容CHD，望更新，谢谢

### ISSUE THREAD

**Issue by z4jst** [Juszoe/flexget-nexusphp#65]
HR标记附近代码（详情页），有HR的种子ID：134937
`<tr><td class="rowhead nowrap" valign="top" align="right">基本信息</td><td class="rowfollow" valign="top" align="left"><b><b>大小：</b></b>11.39 GB&nbsp;&nbsp;&nbsp;<b>类型:</b>&nbsp;Movies&nbsp;&nbsp;&nbsp;<b>媒介:&nbsp;</b>Encode&nbsp;&nbsp;&nbsp;<b>编码:&nbsp;</b>H.264/AVC&nbsp;&nbsp;&nbsp;<b>音频编码:&nbsp;</b>DTS-HD&nbsp;&nbsp;&nbsp;<b>分辨率:&nbsp;</b>1080p&nbsp;&nbsp;&nbsp;<b>制作组:&nbsp;</b>压制组&nbsp;&nbsp;&nbsp;<b>H&R:&nbsp;</b>3</td></tr>`
无HR特殊GIF，无特殊字符，单纯使用H&R匹配会抓取到个人信息中的HR。
个人信息中的HR代码如下：
`<td class="bottom" align="left"><span class="medium">欢迎回来, <span class="nowrap"><a href="userdetails.php?id=***" class='CrazyUser_Name'><b>****</b></a></span> [<a href="logout.php">退出</a>] [<a href="getrss.php">RSS下载</a>] [<a href="torrents.php?inclbookmarked=1&amp;allsec=1&amp;incldead=0">收藏</a>] <font class="color_bonus">魔力值 </font>[<a href="mybonus.php">使用</a>]: **** <font class="color_invite">邀请 </font>[<a href="invite.php?id=****">发送</a>]: 0 <a href='hnr.php?id=****'><font class="color_bonus">H&R:</font></a>1<br />`

**Comment by ma3252788** [comment]
同求

**Comment by Juszoe** [comment]
@z4jst @ma3252788  麻烦测试一下是否适配CHD的HR规则
[nexusphp-issue-65.zip](https://github.com/Juszoe/flexget-nexusphp/files/6752129/nexusphp-issue-65.zip)

**Comment by z4jst** [comment]
谢谢，我周末试一下来反馈。
另外，我临时的解决方案是:
在line:203行
增加hr匹配字段「H&R:&nbsp」，这个也可以。除非chd后期修改格式。
