### ISSUE TITLE
CF 5秒盾怎么解决？

### ISSUE THREAD

**Issue by Iorest** [Juszoe/flexget-nexusphp#66]
我在mteam上使用 flexget-nexusphp时，出现NexusPHP._get_info: 503 Server Error: Service Temporarily Unavailable for url。这种情况怎么解决？

**Comment by Juszoe** [comment]
对于Cloudflare的五秒盾，可以考虑使用Flexget官方内置的插件[cfscraper](https://flexget.com/Plugins/cfscraper)
1. 首先需要安装依赖
``` bash
pip install cloudscraper
```
2. 然后启用
``` yaml
cfscraper: yes
```
